### ISSUE TITLE
Module position in relation to Newsfeed

### ISSUE THREAD

**Issue by DanielWeeber** [shbatm/MMM-RTSPStream#11]
(using wip branch)
I use the player in the bottom left corner. I have the standard newsfeed in the bottom center.
When a two line News is displayed the Border of the Module is display perfectly in line with the video feed. But when the Newsfeed changes to a oneliner the modules "jumps" also down so that the video is out of place.

Any idea how we can fix this? I'm happy to submit a PR if I would have any clue how to fix it.

**Comment by shbatm** [comment]
This should just need to be a change in the css, maybe to make the boundary position fixed instead of absolute?  If you have time/experience you can play with [this part](https://github.com/shbatm/MMM-RTSPStream/blob/wip/MMM-RTSPStream.css#L35) of the CSS to make it fixed and give it an hard coded position, just to see if that would fix the problem.

The relevant part of the code starts around [here](https://github.com/shbatm/MMM-RTSPStream/blob/wip/MMM-RTSPStream.js#L214).

I will look into this myself as I get time the next few weeks.

**Comment by shbatm** [comment]
Due to the nature of how OMXPlayer gets a position on screen, the module should be placed closer to the edges than any module that changes size.  This can be accomplished by changing the order of the modules' config sections in the `config.js` file.
