### ISSUE TITLE
Turn sound off?

### ISSUE THREAD

**Issue by psteimann** [shbatm/MMM-RTSPStream#15]
Hi,

Is there an option to turn off the micro of the webcam?
I'm using omxplayer

**Comment by shbatm** [comment]
I'm sorry for the delayed response.  Could you please test for me?

```shell
cd ~/MagicMirror/modules/MMM-RTSPStream
git fetch --all
git checkout nosound
```

**Comment by alverman** [comment]
when I do the command I see this:

pi@pi3mmm:~/MagicMirror/modules/MMM-RTSPStream $ sudo git checkout nosound
error: Your local changes to the following files would be overwritten by checkout: node_helper.js
Please commit your changes or stash them before you switch branches.
Aborting

for me it is absolutely necessary to enter in the command that opens the flow -n -1 otherwise nothing works.
If you want to take a look at my situation here:
[https://forum.magicmirror.builders/topic/5570/mmm-rtspstream-dosent-work-in-my-case/10](url)

Thank you, Alberto

**Comment by alverman** [comment]
solved !!
