### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by swvalenti194** [shbatm/MMM-RTSPStream#30]
Hello, I am having an issue trying to display my HikVision cameras (DS-2CD2342WD-1).  I am able to see the module but it's black screen and nothing loads.  The sample url doesn't load either.  Pm2 omxstream is online and running.  Below is my config.  Any help would be greatly appreciated.  

{
    module: "MMM-RTSPStream",
    position: "middle_center",
    config: {
        autoStart: true,
        rotateStreams: true,
        rotateStreamTimeout: 10,
        moduleWidth: 354,
        moduleHeight: 240,
        localPlayer: 'omxplayer',
        remotePlayer: 'none',
        showSnapWhenPaused: true,
        remoteSnaps: true,
        stream1: {
            name: 'Driveway',
            url: 'rtsp://XXXX:XXXXXX@192.168.0.40:10554//Streaming/Channels/1',
            frameRate: 'undefined',
            snapshotType: 'url',
            snapshotRefresh: 10,
            width: undefined,
            height: undefined,
            },
        }
},

**Comment by swvalenti194** [comment]
I forgot to note that I can get my cameras to play in VLC with no issue

**Comment by shbatm** [comment]
A couple things to try first (sorry, I'm away from my main computer and can't do any detailed troubleshooting this week): 
1) Confirm you're looking at the actual display connected to the Pi, not over VLC.
2) Check the PM2 log for errors--(use `pm2 log mm` from ssh to stream the log or look in `~/.pm2/logs/`)
2) change `frameRate: 'undefined'` to `frameRate: undefined`.
2) Try Channel 2 on the camera (lower res) and see if that works. Sometimes OMX chokes on the high-res (change the 1 to a 2 at the end of the url).
3) Try increasing the GPU memory split in `raspi-config`
4) Make sure the Pi is connecting to the camera correctly--set `autoStart: false` and add `snapshotUrl: 'http://XXXX:XXXXXX@192.168.0.40:80//Streaming/Channels/2/picture',` below the url.
6) Check [this thread](https://forum.magicmirror.builders/topic/2743/mmm-rtspstream-video-streaming-from-live-feeds-security-cameras/) around page 10 for a couple other potential solutions.

**Comment by swvalenti194** [comment]
The cameras rotate thought but something is not right they are on like a rapid fire sequence....set to 15 for stream timeout.....any ideas?

**Comment by swvalenti194** [comment]
Also how do you make omx_streams start automatically when the pi loses power or reboots?  Sorry for all these noobish questions

**Comment by swvalenti194** [comment]
pulling whatever little hair i have left out...now video doesnt show and i get a black screen with a play button

**Comment by shbatm** [comment]
Change `autoStart` back to `true` to get the streams starting when MM loads. `false` was just to check if the snapshots could load.  Background: to reduce load, with `autoStart: false,` you can have it display snapshots from the cameras every X seconds until you click the play button to play the streams (if you provide a snapshot url).

If you're having issues getting the streams to start automatically just by using `autoStart` then once you get everything playing correctly, type `pm2 save` in SSH/terminal to save the current state across reboots.

I honestly haven't played with rotating single streams since switching from ffmpeg to omxplayer. Try setting the timeout longer to see if it helps, or if you have room, `rotateStreams: false` will show all 3 at the same time (increase your GPU split to make sure omxplayer doesn't choke on one).

For alignment, refer to the README and look at `moduleOffset` and `absPosition` settings.

**Comment by swvalenti194** [comment]
is it possible the the rotate stream is in milliseconds and not seconds?

**Comment by shbatm** [comment]
I double checked that, there's a x1000 multiplier everywhere there needs to be. I think the issue has to do with pm2 not properly stopping the streams, I'm going to try a workaround this weekend when I get a chance.

**Comment by swvalenti194** [comment]
Thank you sir, that would make more sense.

**Comment by shbatm** [comment]
OK, I tested a few things and, in general, rotate streams was working OK on my mirror. the only real issue was the delay between omxplayer stopping one stream and starting another. 

I did have an issue where one stream was not stopping properly and then I restarted the mirror. It looked like it was trying to play both videos on top of one another... which sounds like what you were seeing.

I pushed an update to the `wip` branch to try and fix the glitch where the camera streams do not stop when you exit or restart the MagicMirror instance.  My recommendation would be to do the following and let me know if you are still seeing the issue:

1. Set your rotate stream timeout to a minimum of 10 (seconds)
2. Stop all PM2 instances (`pm2 kill`)
3. Switch to the `wip` branch: 
    ```shell
    cd ~/MagicMirror/modules/MMM-RTSPStream/
    git fetch --all
    git checkout wip
    npm install
    ```
4. Update your global PM2 version `sudo npm install -g pm2`
5. Restart the MagicMirror instance.

While troubleshooting, it may help to monitor the PM2 logs in a separate ssh window (`pm2 logs`) and make sure it's actually stopping one stream (should see a line with blue text about stopping an instance of omx_stream1) and starting another.

**Comment by swvalenti194** [comment]
That worked sir thank you for investing your time to fix this.

**Comment by swvalenti194** [comment]
Well, now that I am on the wip branch it seems the mirror only works for couple hours before it loses internet connection.  I have to power cycle it to be able to gain access to it again.

**Comment by shbatm** [comment]
Please try and update to the `develop` branch and see if you're still having issues.

**Comment by swvalenti194** [comment]
Ok, how do I do that?

**Comment by shbatm** [comment]
Same thing as above, except `develop` instead of `wip`

**Comment by swvalenti194** [comment]
Thanks, I switched and will let you know.  I tried making the module video feed larger on my mirror to no avail.  Changed default of module width and height to 640 and 480 but size didnt change?

**Comment by shbatm** [comment]
Set the width and height in the stream settings as well.

**Comment by sepulvar** [comment]
I still do not get how to display my camera. It works well on VLC medial player as well as through omxplayer command in my Raspberry Pi. So I think I have omxplayer working well. 

I increased GPU Memory to 400. 

rtsp://xxxxx:xxxxx@10.80.1.81/cam1/onvif-h264

I only get the black box with no content when I run my code:

		{
   		module: "MMM-RTSPStream",
    		position: "top_center",
    		header: "Live View",
  	     	config: {

			autoStart: true,
			rotateStreams: true,
			rotateStreamTimeout: 10,
			moduleWidth: 354,
			moduleHeight: 240,
			localPlayer: 'omxplayer',
			remotePlayer: 'none',
			showSnapWhenPaused: false,			
			remoteSnaps: false,
        		
        		stream1: {
            			name: 'R2D2 Garage',
				url: 'rtsp://xxx:xxx@10.80.1.81/cam1/onvif-h264',
            			frameRate: undefined,
				width: undefined,
				height: undefined,
            			},
        		},
		},

What else am I missing?

Thanks

**Comment by sepulvar** [comment]
When the black box shows, I position cursor on top and hit play and my camera shows as expected. I have autoStart: true, ... how can I get the camera to display when I run pm2 start MagicMirror command? or the Pi reboots and MagicMirror starts automatically? in other words, I do not want to have to press play to display the camera. Thanks
