### ISSUE TITLE
Simple plain HTML code to show onvif Cameras on browser

### ISSUE THREAD

**Issue by pooyasa** [shbatm/MMM-RTSPStream#50]
Hi
I'm currently using this module and it works perfectly.
The problem is, this module is way too complicated for me to tweak or even understand.

I'm turning the Magic Mirror into an home automation device and I'm running a web server on it so that I can control the lights and curtains via the web server. I want to add a feature to my web page to watch RTSP cameras.
I've done a lot of research and the closest thing I found was how to watch the camera via VLC mediaplayer, but I want the frame to be inside the HTML code.

So, what I'm asking is, can you please give me a simple plain code to put on my webpage so I can watch live streams from cameras?
something like this:

<video width="400" controls>
  <source src="rtsp://user:password@192.168.1.106:554/onvif1" type="video/mp4">
  Your browser does not support HTML5 video.
</video>

 As you have done this before for this module.

Thank you very much
Pooya Sajjadi

**Comment by shbatm** [comment]
@pooyasa -- For that you're better off looking into the actual libraries behind this repo.  Specifically, I use node-rtsp-stream-es6 to stream cameras from RTSP.  RTSP and web browsers no longer play very nice since NSAPI was removed from most mainstream browsers which killed most live-stream no-transcode plugins.

If you're using Python for a webserver another option is the `av` PyPi library.

Sorry, but I really can't provide much more help than that.
