### ISSUE TITLE
rtsp protocol slow lag issue

### ISSUE THREAD

**Issue by sainiaj** [shbatm/MMM-RTSPStream#8]
Hi shbatm,

Thank you making this awesome module, now i can add stream to my magic mirror,
my only question is i am using cheap ebay $30 usd camera they supports rtsp,
camera specs
2 mp 
1920 x 1080 video quality decent image quality 

when i stream rtsp url on vlc or my phone the lag is very minimum or none 
however on raspberry pi its way to much (5 to 8 sec) i was wondering it is the module it self or the protocol

Thank you

**Comment by shbatm** [comment]
Most likey it's the module causing the lag. I've been testing some alternate methods for reducing this. If you are showing the video on the screen attached to the pi (as opposed to a browser on another computer) you can try the wip branch which uses omxplayer to play instead of ffmpeg. See this thread for details... https://forum.magicmirror.builders/topic/2743/mmm-rtspstream-video-streaming-from-live-feeds-security-cameras/10

**Comment by shbatm** [comment]
This should be fixed now when using hardware-accelerated playback with OMXPlayer. Please update the module and test, re-open if necessary.  Please note, there is still some lag when using FFMPEG for remote streams, at this point, this is unavoidable due to the nature of the processing; that is why OMXPlayer has been chosen as the default.
