### ISSUE TITLE
Black Display

### ISSUE THREAD

**Issue by classic079** [shbatm/MMM-RTSPStream#9]
I'm trying to get this up and working using the default information in the config which I verified the RTSP stream still works prior to loading. When I load though it comes up blank. I think it has something to do with ffmpeg but I'm a complete noob and have no idea what to do. This is the error I'm seeing in red when I try to launch magic mirror which I think is the issue. I've tried a couple times to install ffmpeg but still getting this same error.  

WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'datauri'

Do you have any idea what I can do? Is there a way we can grab like 1 frame a second so I can run like 8 cameras on it around the outside of the mirror? 

Thanks for all your help and this awesome project! Its the whole reason I started trying to build a mirror.

**Comment by shbatm** [comment]
@classic079 - did you remember to run the following?
```js
cd ~/MagicMirror/modules/MMM-RTSPStream
npm install
```

> Is there a way we can grab like 1 frame a second so I can run like 8 cameras on it around the outside of the mirror?

This is definitely possible (it's what I do) and there are a couple ways to do it: the easiest way to do this is if your cameras support a "snapshot" url or file saving.  You can add this in the stream config (see [this section](https://github.com/shbatm/MMM-RTSPStream#stream-configuration-options) of the config options, especially the `snapshotUrl`, `snapshotType`, and `snapshotRefresh` options).  If you can't figure it out, let me know the model of your camera's and I'll take a look.

Here is a Gist with my multi-camera setup config (the one in the screenshot on the main page), note you'll need to adjust the module size to fit all of your cameras: https://gist.github.com/shbatm/f02569e21738eccc71a51a81775c66b8

By setting `autoStart: false` and `showSnapWhenPaused: true`, the module will pull the snapshot images and will only show the video stream when you click the individual video (or via module notification--advanced).  By setting `rotateStreams: false` it will display all the cameras simultaneously in their own windows instead of looping through them in one box.

Side note: you may also want to see the other Issues about video lag and using the `wip` branch of this module; with 8 cameras you'll probably be affected if you're trying to play all of them at once (but you should be OK using snapshots described above).

**Comment by classic079** [comment]
That was exactly my problem, thank you! As far as snapshot I'm thinking the
easiest way to do that is is to use Blue Iris software. Most of my Cameras
are CCTV so I need a way to convert them and since I'm already using blue
iris for ip cameras I figured that was the route to take. I bought a PCI
card to input my CCTV to it. If we can get snapshot working on blue iris
which I'm sure there is a way then all of my camera info should be very
easy to pull.

Thank, John!
